global:
  INIT_MYSQL_ROOT_PASSWORD: 
  INIT_ADMIN_EMAIL: 
  INIT_ADMIN_PASSWORD: 
  JWT_PRIVATE_KEY: 
  MYSQL_PASSWORD: 
  MYSQL_HOST: mysql
  MYSQL_PORT: 3306
  MYSQL_USER: seaticket
  MYSQL_DB: seaticket_db
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_PASSWORD:
  S3_HOST: 
  S3_FILE_BUCKET: 
  S3_WEB_CRAWL_BUCKET: 
  S3_KEY_ID: 
  S3_SECRET_KEY: 
  SEADB_INNER_SERVER_URL: http://seadb:8888
  SEAQA_AI_INNER_SERVER_URL: http://seaqa-ai:8887
  SEAQA_INDEXER_INNER_SERVER_URL: http://seaqa-indexer:8888
