services:
  seaqa-ai:
    image: ${SEAQA_AI_IMAGE:-seaticket/seaqa-ai:0.1.0-testing}
    restart: unless-stopped
    container_name: seaqa-ai
    ports:
      - 8887:8887
    volumes:
      - ./config.yml:/opt/seaticket/conf/config.yml:ro
      - ${SEATICKET_VOLUME:-/opt/seaticket-data}:/shared
    environment:
      - SEAQA_LOG_TO_STDOUT=${LOG_TO_STDOUT:-false}
      - TZ=${TIME_ZONE:-UTC}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY:?Variable is not set or empty}
      - SEADB_SERVER_URL=${SEADB_SERVER_URL:-seadb}
      - SEADB_SERVER_ACCESS_TOEKN=${SEADB_SERVER_ACCESS_TOEKN:?Variable is not set or empty}
      - SEAQA_MYSQL_DB_HOST=${SEAQA_MYSQL_DB_HOST:?Variable is not set or empty}
      - SEAQA_MYSQL_DB_PORT=${SEAQA_MYSQL_DB_PORT:-3306}
      - SEAQA_MYSQL_DB_USER=${SEAQA_MYSQL_DB_USER:-seaticket}
      - SEAQA_MYSQL_DB_PASSWORD=${SEAQA_MYSQL_DB_PASSWORD:-}
      - SEAQA_MYSQL_SEAQA_DB_NAME=${SEAQA_MYSQL_SEAQA_DB_NAME:-seaticket_db}
      - REDIS_HOST=${REDIS_HOST:?Variable is not set or empty}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - S3_HOST=${S3_HOST:?Variable is not set or empty}
      - S3_WEB_CRAWL_BUCKET=${S3_WEB_CRAWL_BUCKET:?Variable is not set or empty}
      - S3_KEY_ID=${S3_KEY_ID:?Variable is not set or empty}
      - S3_SECRET_KEY=${S3_SECRET_KEY:?Variable is not set or empty}
    networks:
      - backend-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8887 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  backend-net:
    name: backend-net
