global:
  JWT_PRIVATE_KEY: 
  SEAQA_MYSQL_DB_HOST: 192.168.0.12
  SEAQA_MYSQL_DB_PORT: 3306
  SEAQA_MYSQL_DB_USER: seaticket
  SEAQA_MYSQL_DB_PASSWORD: 
  SEAQA_MYSQL_SEAQA_DB_NAME: seaticket_db
  REDIS_HOST: 192.168.0.13
  REDIS_PORT: 6379
  REDIS_PASSWORD:
  S3_HOST: 
  S3_FILE_BUCKET: 
  S3_WEB_CRAWL_BUCKET: 
  S3_KEY_ID: 
  S3_SECRET_KEY: 
  SEASEARCH_URL: http://192.168.0.21:4080
  SEASEARCH_TOKEN: 
  SEADB_INNER_SERVER_URL: http://192.168.0.22:8888
  SEAQA_AI_INNER_SERVER_URL: http://192.168.0.23:8887
  SEAQA_INDEXER_INNER_SERVER_URL: http://192.168.0.24:8888
  LLM_MODELS:
    - type: 
      key: 
      model: 
      label: 
seaqa-ai:
  EMBEDDING_MODEL:
    type: 
    url: 
    key: 
    model: 
